# Generated by Django 4.1.1 on 2023-01-03 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0002_alter_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="categories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
